# Generated by Django 5.2.3 on 2025-06-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galgo',
            fields=[
                ('perro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adopcion.perro')),
            ],
            bases=('adopcion.perro',),
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado')], default='disponible', max_length=15),
        ),
        migrations.AlterField(
            model_name='perro',
            name='vacunado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UsuarioAdoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('preferencias_raza', models.CharField(blank=True, max_length=50)),
                ('preferencias_edad', models.PositiveIntegerField(blank=True, null=True)),
                ('preferencias_tamano', models.CharField(blank=True, max_length=50)),
                ('historial_adopciones', models.ManyToManyField(blank=True, to='adopcion.perro')),
            ],
        ),
    ]
