# Generated by Django 5.2.3 on 2025-06-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_galgo_alter_perro_estado_alter_perro_vacunado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
